; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   	; (the path to the socket file)
chmod=0766                      	; socket file mode (default 0766)

[supervisord]
logfile=/container/logs/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid 			; (supervisord pidfile;default supervisord.pid)
childlogdir=/container/logs/supervisor             ; ('AUTO' child log dir, default $TEMP)
umask=022

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock 	; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[supervisord]
nodaemon=true

[program:rsyslog]
command=rsyslogd -n -f /container/config/rsyslog.conf
stdout_logfile=/container/logs/supervisor/%(program_name)s-stdout.log
stderr_logfile=/container/logs/supervisor/%(program_name)s-stderr.log

[program:nginx]
command=/usr/sbin/nginx
stdout_logfile=/container/logs/supervisor/%(program_name)s-stdout.log
stderr_logfile=/container/logs/supervisor/%(program_name)s-stderr.log

[program:cron]
command=/bin/bash -c "touch /etc/crontab && cron -f"
stdout_logfile=/container/logs/supervisor/%(program_name)s-stdout.log
stderr_logfile=/container/logs/supervisor/%(program_name)s-stderr.log

[program:nodejs]
environment=HOME=/opt/penpot/exporter ; $HOME variable is used by npm for logging and caching
command=/usr/local/bin/node /opt/penpot/exporter/app.js
stdout_logfile=/container/logs/supervisor/%(program_name)s-stdout.log
stderr_logfile=/container/logs/supervisor/%(program_name)s-stderr.log
user=www-data

[program:penpot]
environment=HOME=/opt/penpot/backend
command=/bin/bash -c "cd /opt/penpot/backend && /opt/penpot/backend/run.sh"
stdout_logfile=/container/logs/supervisor/%(program_name)s-stdout.log
stderr_logfile=/container/logs/supervisor/%(program_name)s-stderr.log